services:
  webdav:
    image: derkades/webdav
    volumes: ['/Users/ghio/kDrive/webdav_zotero:/data']
    ports: ['8080:80']
    environment:
      USERNAME: webdavuser
      PASSWORD: webdavpass
    restart: unless-stopped